apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chart.name }}
  namespace: {{ .Values.chart.namespace }}
  labels:
    app: {{ .Values.chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.chart.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.chart.name }}
    spec:
      containers:
      - name: {{ .Values.chart.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}