replicaCount: 1

chart:
  name: db
  namespace: iip

image:
  repo: postgres
  tag: 17-alpine

service:
  type: ClusterIP
  port: 5432

auth:
  username: admin
  password: admin
  database: admin

environment: dev