replicaCount: 1

chart:
  name: frontend
  namespace: iip

image:
  repo: ghcr.io/intens-intern-project/frontend/frontend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: github-packages-secret

service:
  type: ClusterIP
  port: 80