apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chart.name }}
  namespace: {{ .Values.chart.namespace }}
  labels:
    app: {{ .Values.chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.chart.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.chart.name }}
    spec:
      containers:
      - name: {{ .Values.chart.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}

        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: pvc
          mountPath: /var/lib/postgresql/data
    
        envFrom:
          - secretRef:
              name: {{ .Values.chart.name }}

      volumes:
        - name: initdb
          configMap:
            name: {{ .Values.chart.name }}-initdb
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ .Values.chart.name }}-pvc