apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.chart.name }}-pvc
  namespace: {{ .Values.chart.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard