replicaCount: 1

chart:
  name: backend
  namespace: iip

image:
  repo: ghcr.io/intens-intern-project/backend/backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: github-packages-secret

service:
  type: ClusterIP
  port: 8080