replicaCount: 2

chart:
  name: backend
  namespace: iip

image:
  repo: ghcr.io/intens-intern-project/backend
  tag: "latest"
  imagePullPolicy: Always

imagePullSecrets:
  - name: github-packages-secret

service:
  type: ClusterIP
  port: 8080

environment: dev