apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iip-org-runner-cluster-role
rules:
  # Read access to everything
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Full access to deployments and replicasets
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iip-org-runner-sa
  namespace: arc-runners
---
# [dev] environment
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iip-org-runner-role-binding-dev
  namespace: iip-dev
subjects:
  - kind: ServiceAccount
    name: iip-org-runner-sa
    namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: iip-org-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# [prod] environment
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iip-org-runner-role-binding-prod
  namespace: iip-prod
subjects:
  - kind: ServiceAccount
    name: iip-org-runner-sa
    namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: iip-org-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io