name: Deploy application
on:
  push:
    branches:
      - main
      - dev

env:
  TF_CHARTS_VAR_NAME: helm_chart_versions
  ORG_OWNER: magley
  HELM_REMOTE: oci://ghcr.io/intens-intern-project

jobs:
  deploy:
    runs-on: iip-org-runner
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Determine Staging Environment
        run: |
          case "$GITHUB_REF_NAME" in
            main)
              echo "TFVARS_FILE=prod.tfvars" >> "$GITHUB_ENV"
              ;;
            dev)
              echo "TFVARS_FILE=dev.tfvars" >> "$GITHUB_ENV"
              ;;
            *)
              echo "Unsupported branch: $GITHUB_REF_NAME"
              exit 0
              ;;
          esac
          echo Will use $TFVARS_FILE for deployment

      - name: Helm Init
        uses: azure/setup-helm@v4
        with:
          version: '3.20.0'

      - name: Login to Helm
        run: |
          helm registry login ghcr.io \
            -u "${{ env.ORG_OWNER }}" \
            --password-stdin <<< "${{ secrets.HELM_TOKEN }}"

      - name: Build and Push Helm Charts
        run: './ci/helm_publish.sh ./helmcharts ${{ env.HELM_REMOTE }}'

      - name: Get Helm Chart Versions
        run: |
          versions=$(./ci/get_chart_versions.sh)
          echo $versions
          echo TF_VAR_${{ env.TF_CHARTS_VAR_NAME }}=$versions >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -var-file=$TFVARS_FILE