name: Deploy application
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: iip-org-runner
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve