name: Test workflow
on:
  workflow_dispatch:

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  first-and-only-job:
    runs-on: iip-org-runner
    steps:
    # - name: Say hello
    #   run: echo "Hello from local runner"

    # - name: Install kubectl
    #   uses: azure/setup-kubectl@v5.1.0
    #   with:
    #     version: v1.36.1

    # - name: Test if kubectl is working
    #   run: kubectl get all -n iip

    - name: Checkout Repo
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.15.7"

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve