name: Validate IaC
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: iip-runner-set
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

