name: Validate IaC
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan -var-file=$TFVARS_FILE

      - name: Generate Readable Plan
        run: |
          cd terraform
          terraform show -no-color tfplan > plan.txt

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Terraform plan
          path: terraform/plan.txt

      - name: Helm Init
        uses: azure/setup-helm@v4
        with:
          version: '3.20.0'

      - name: Helm Lint
        run: ./ci/helm_lint.sh ./helmcharts